# Generated by Django 5.0.6 on 2024-07-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_navbar_name_alter_navbar_links_alter_navbar_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/_bg'),
        ),
    ]
