# Generated by Django 5.0.6 on 2024-07-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='service',
        ),
    ]
