# Generated by Django 5.0.6 on 2024-07-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_services_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-updated', 'created']},
        ),
    ]
