# Generated by Django 5.0.6 on 2024-07-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_service_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='services',
        ),
    ]
