# Generated by Django 5.0.6 on 2024-07-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_service_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='services',
            new_name='CompanyService',
        ),
    ]
