# Generated by Django 5.0.6 on 2024-07-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_services_companyservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyservice',
            options={},
        ),
        migrations.RemoveField(
            model_name='companyservice',
            name='title',
        ),
        migrations.AddField(
            model_name='companyservice',
            name='name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
