# Generated by Django 5.0.6 on 2024-07-04 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_companyservice_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyService',
        ),
    ]
