# Generated by Django 5.0.6 on 2024-07-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_companyservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyservice',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
