# Generated by Django 5.0.6 on 2024-07-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_companyservice_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavBar',
        ),
    ]
