# Generated by Django 5.0.6 on 2024-07-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_navbar'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/_bg')),
                ('name', models.CharField(max_length=100, null=True)),
                ('links', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
