# Generated by Django 5.0.2 on 2024-07-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='content',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
