# Generated by Django 5.0.2 on 2024-07-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_companyservice_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyservice',
            name='content',
            field=models.TextField(max_length=350, null=True),
        ),
    ]
