# Generated by Django 5.0.2 on 2024-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_companyservice_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyservice',
            name='content',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
