# Generated by Django 5.0.2 on 2024-07-06 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_companyservice_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyservice',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/_icons/'),
        ),
    ]
