# Generated by Django 5.0.6 on 2024-07-07 09:28

import base.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyservice',
            name='icon',
            field=base.fields.SVGAndImageField(blank=True, null=True, upload_to='static/images/_icons/'),
        ),
    ]
