# Generated by Django 5.0.6 on 2024-07-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_companyservice_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyservice',
            options={'ordering': ['-updated', 'created']},
        ),
    ]
