# Generated by Django 5.0.6 on 2024-07-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_companyservice_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyservice',
            name='icon',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
