# Generated by Django 5.0.6 on 2024-07-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_companyservice_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyservice',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
