# Generated by Django 5.0.6 on 2024-07-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_companyservice_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyservice',
            name='icon',
        ),
        migrations.AddField(
            model_name='companyservice',
            name='iconURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
