# Generated by Django 5.0.6 on 2024-07-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_companyservice_icon_companyservice_iconurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyservice',
            name='iconURL',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
