# Generated by Django 5.0.6 on 2024-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_companyservice_iconurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyservice',
            name='iconURL',
        ),
        migrations.AddField(
            model_name='companyservice',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
