# Generated by Django 5.0.6 on 2024-07-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_navbar_links_navbar_urlname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='logo',
        ),
    ]
