# Generated by Django 5.0.6 on 2024-07-08 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_navbar_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstsection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firstsection',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='firstsection',
            name='title',
            field=models.CharField(max_length=70),
        ),
    ]
