# Generated by Django 5.0.6 on 2024-07-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_firstsection_created_firstsection_updated_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstsection',
            options={'ordering': ['created']},
        ),
    ]
