# Generated by Django 5.0.6 on 2024-07-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_firstsection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstsection',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
