# Generated by Django 5.0.2 on 2024-07-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_pagescontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstsection',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
