# Generated by Django 5.0.6 on 2024-07-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_careers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
