# Generated by Django 5.0.2 on 2024-07-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_careers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careers',
            name='image',
            field=models.ImageField(blank=True, default='images/_bg/default.jpg', null=True, upload_to='images/_bg'),
        ),
    ]
